name: Linear Ticket Check

on:
  pull_request_target:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  linear-ticket:
    permissions:
      pull-requests: write
      issues: write
    uses: TryLity-Automation-Solutions/.github/.github/workflows/linear-ticket-check.yml@main
    secrets: inherit
